### ISSUE TITLE
Uncaught (in promise) RuntimeError: unreachable

### ISSUE THREAD

**Issue by spartucus** [nalinbhardwaj/halo-wordle#2]
Great work! 

Although it seems that something wrong when run test. 

Env:
* Chrome: 103.0.5060.114(x86_64)
* Mac 12.4(Intel)
* node v18.6.0

Here are logs:
```
react-dom.development.js:29840 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
DevTools failed to load source map: Could not load content for chrome-extension://bjiiiblnpkonoiegdlifcciokocjbhkd/sourcemaps/portal-contentscript.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://bjiiiblnpkonoiegdlifcciokocjbhkd/sourcemaps/portal-inpage.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
halo-worker.ts:4 diffing
App.tsx:17 in between (6) [Array(2), Array(2), Array(2), Array(2), Array(2), Array(2)]
App.tsx:18 btw 125.23499999940395
halo-worker.ts:22 param length 1711
halo-worker.ts:23 params Uint8Array(1711) [60, 33, 68, 79, 67, 84, 89, 80, 69, 32, 104, 116, 109, 108, 62, 10, 60, 104, 116, 109, 108, 32, 108, 97, 110, 103, 61, 34, 101, 110, 34, 62, 10, 32, 32, 60, 104, 101, 97, 100, 62, 10, 32, 32, 32, 32, 60, 109, 101, 116, 97, 32, 99, 104, 97, 114, 115, 101, 116, 61, 34, 117, 116, 102, 45, 56, 34, 32, 47, 62, 10, 32, 32, 32, 32, 60, 108, 105, 110, 107, 32, 114, 101, 108, 61, 34, 105, 99, 111, 110, 34, 32, 104, 114, 101, 102, 61, 34, 47, 102, …]
halo-worker.ts:25 genning proof
halo-worker.ts:31 here we go
wordle_bg.a4fc301cf35a6c6e6137.wasm:0xf8cae Uncaught (in promise) RuntimeError: unreachable
    at wordle_bg.a4fc301cf35a6c6e6137.wasm:0xf8cae
    at wordle_bg.a4fc301cf35a6c6e6137.wasm:0xb804c
    at wordle_bg.a4fc301cf35a6c6e6137.wasm:0xf4ad6
    at wordle_bg.a4fc301cf35a6c6e6137.wasm:0xda951
    at wordle_bg.a4fc301cf35a6c6e6137.wasm:0x40fba
    at wordle_bg.a4fc301cf35a6c6e6137.wasm:0xb522f
    at wordle_bg.a4fc301cf35a6c6e6137.wasm:0xccc2b
    at wordle_bg.a4fc301cf35a6c6e6137.wasm:0xf9438
    at __wbg_adapter_30 (wordle.js:138:1)
    at real (wordle.js:123:1)
$func783 @ wordle_bg.a4fc301cf35a6c6e6137.wasm:0xf8cae
$func268 @ wordle_bg.a4fc301cf35a6c6e6137.wasm:0xb804c
$func735 @ wordle_bg.a4fc301cf35a6c6e6137.wasm:0xf4ad6
$func589 @ wordle_bg.a4fc301cf35a6c6e6137.wasm:0xda951
$func57 @ wordle_bg.a4fc301cf35a6c6e6137.wasm:0x40fba
$func251 @ wordle_bg.a4fc301cf35a6c6e6137.wasm:0xb522f
$func416 @ wordle_bg.a4fc301cf35a6c6e6137.wasm:0xccc2b
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__haef9329f49c97952 @ wordle_bg.a4fc301cf35a6c6e6137.wasm:0xf9438
__wbg_adapter_30 @ wordle.js:138
real @ wordle.js:123
Promise.then (async)
imports.wbg.__wbg_then_1c698eedca15eed6 @ wordle.js:470
$func862 @ wordle_bg.a4fc301cf35a6c6e6137.wasm:0xf9ca8
$func374 @ wordle_bg.a4fc301cf35a6c6e6137.wasm:0xc80c7
$wasm_bindgen__convert__closures__invoke2_mut__hd4573d3b0ab790e5 @ wordle_bg.a4fc301cf35a6c6e6137.wasm:0xf93bb
__wbg_adapter_81 @ wordle.js:198
cb0 @ wordle.js:454
imports.wbg.__wbg_new_78403b138428b684 @ wordle.js:459
$func913 @ wordle_bg.a4fc301cf35a6c6e6137.wasm:0xfa514
$prove_play @ wordle_bg.a4fc301cf35a6c6e6137.wasm:0xdb5c2
prove_play @ wordle.js:182
prove_play @ halo-worker.ts:32
await in prove_play (async)
callback @ comlink.ts:312

```

**Comment by nalinbhardwaj** [comment]
Does the deployed version at https://zordle.xyz also crash with the same error for you? My suspicion is your browser isn't able to allocate enough memory necessary for these proofs.
You can also get better traces (at the expense of it taking significantly longer) by appending `--debug` to the end of [this build command](https://github.com/nalinbhardwaj/zordle/blob/main/test-client/package.json#L71) and rebuilding the Wasm port which will help significantly narrow down the issue.

**Comment by spartucus** [comment]
Thanks for reply! That makes sense, I will try `--debug`.

**Comment by spartucus** [comment]
`--dev` really helps a lot! 
It turns out I ran `test-client` without 'params.bin', after I copy it from `react-wordle`, everything works fine.
